### ISSUE TITLE
Can I use the name "bs-vscode" on npm?

### ISSUE THREAD

**Issue by banacorn** [glennsl/bs-vscode#1]
I have a [huge VS Code binding](https://github.com/banacorn/bs-vscode/blob/main/src/VSCode.re) in progress and I wish to publish it to the npm registry.

It would be nice if I could release it under the name `bs-vscode`.

**Comment by glennsl** [comment]
Hey. I don't think it's a good idea to reuse package names as it might break existing users and could even open up for security vulnerabilities. Instead you should namespace your package, as I've since done with [other packages of mine](https://www.npmjs.com/search?q=%40glennsl), and should have done with this one as well.

I also think the `bs-` prefix has been deprecated since BuckleScript has been renamed rescript. As I understand the consensus is to use `rescript-` now.
